GroupProject/Controllers/UserReadingActivityController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GroupProject.Controllers
{
    public class UserReadingActivityController : Controller
    {
        UserReadingActivityManager userReadingActivityManager = new UserReadingActivityManager(new EfUserReadingActivityRepository());
        ReadingActivityManager readingActivityManager = new ReadingActivityManager(new EfReadingActivityRepository());
        Context c = new Context();
        private static bool activitySortAsc = false;

        // Kullanıcılar etkinliğe katıl butonuna basınca 
        [HttpPost]
        public IActionResult UserJoinActivity(UserReadingActivity activity)
        {
            Context c = new Context();
            var userMail = User.Identity.Name;
            var userID = c.Users.Where(x => x.UserMail == userMail).Select(y => y.UserID).FirstOrDefault();

            bool isUserRegistered = c.UserReadingActivities.Any(x => x.UserID == userID && x.ReadingActivityID==activity.ReadingActivityID);
            if (isUserRegistered)
            {
                // Kullanıcı zaten kayıtlı ise işlemi durdur ve uygun bir yanıt döndür
                return Content("<script>alert('Bu etkinliğe zaten kayıtlı olduğunuz için tekrar kaydolamazsınız.');</script>");
            }

            activity.UserID = userID;
            userReadingActivityManager.TAdd(activity);
            var jsonActivity = JsonConvert.SerializeObject(activity);
            return Json(jsonActivity);
        }

        // Kullanıcı paneli katıldığım etkinlikler listesi
        public IActionResult ActivityIJoin(string sort)
        {
            var userMail = User.Identity.Name;
            var userID = c.Users.Where(x => x.UserMail == userMail).Select(y => y.UserID).FirstOrDefault();
            var model = userReadingActivityManager.GetListofActivityInfo(userID);
            switch (sort)
            {
                case "ActivityTitle":
                    if (activitySortAsc)
                    {
                        model = model.OrderByDescending(r => r.ReadingActivity.ActivityTitle).ToList();
                    }
                    else
                    {
                        model = model.OrderBy(r => r.ReadingActivity.ActivityTitle).ToList();
                    }
                    activitySortAsc = !activitySortAsc;
                    break;
                case "ActivityTitleDESC":
                    break;
                case "ActivityContentASC":
                    model = model.OrderBy(r => r.ReadingActivity.ActivityContent).ToList();
                    break;
                case "ActivityContentDESC":
                    model = model.OrderByDescending(r => r.ReadingActivity.ActivityContent).ToList();
                    break;
                case "ActivityStartDateASC":
                    model = model.OrderBy(r => r.ReadingActivity.ActivityStartDate).ToList();
                    break;
                case "ActivityStartDateDESC":
                    model = model.OrderByDescending(r => r.ReadingActivity.ActivityStartDate).ToList();
                    break;
                case "ActivityFinishDateASC":
                    model = model.OrderBy(r => r.ReadingActivity.ActivityFinishDate).ToList();
                    break;
                case "ActivityFinishDateDESC":
                    model = model.OrderByDescending(r => r.ReadingActivity.ActivityFinishDate).ToList();
                    break;
                case "NumberOfPagesDateASC":
                    model = model.OrderBy(r => r.NumberOfPages).ToList();
                    break;
                case "NumberOfPagesDESC":
                    model = model.OrderByDescending(r => r.NumberOfPages).ToList();
                    break;
                case "BookReviewScoreASC":
                    model = model.OrderBy(r => r.BookReviewScore).ToList();
                    break;
                case "BookReviewScoreDESC":
                    model = model.OrderByDescending(r => r.BookReviewScore).ToList();
                    break;
                default:
                    model = model.OrderByDescending(r => r.BookReviewScore).ToList();
                    break;
            }
            return View(model);
        }

        // Kullanıcı panelinde katıldığım etkinlik bilgisi güncelleme (sayfa sayısı-kitap puanı)
        [HttpGet]
        public IActionResult EditActivity(int id)
        {
            
            UserReadingActivity userReadingActivity = userReadingActivityManager.TGetById(id);
            return View(userReadingActivity);
        }
        [HttpPost]
        public IActionResult EditActivity(UserReadingActivity p)
        {
            Context c = new Context();           
            userReadingActivityManager.TUpdate(p);
            return RedirectToAction("ActivityIJoin");
        }
    }
}

GroupProject/Views/UserReadingActivity/ActivityIJoin.cshtml
@model IEnumerable<EntityLayer.Concrete.UserReadingActivity>
@{
    ViewData["Title"] = "ActivityIJoin";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}


<style>
    .btn-a {
        border: 2px solid #E3E6F0;
        background-color: transparent;
        color: #E3E6F0;
        color: #000;
    }

        .btn-a:hover {
            background-color: #E3E6F0;
            color: #000;
        }
</style>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row">
            <div class="col-sm-6">
                <h6 class="m-0 font-weight-bold text-primary mt-2">KATILDIĞIM ETKİNLİKLER</h6>
            </div>
            @*<div class="col-sm-6">
                <a href="" class="btn btn-success btn-icon-split mr-3" style="float:right">
                    <span class="icon text-white-50">
                        <i class="fas fa-plus"></i>
                    </span>
                    <span class="text">YENİ KİTAP EKLE</span>
                </a>
            </div>*@
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="dropdown show mb-2 col-lg-2">
                <a class="btn btn-a form-control dropdown-toggle" href="#" role="button" id="sortDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Sırala
                </a>
                <div class="dropdown-menu" aria-labelledby="sortDropdown">
                    <a class="dropdown-item" href="?sort=ActivityTitleASC">Etkinlik Adı (A-Z)</a>
                    <a class="dropdown-item" href="?sort=ActivityTitleDESC">Etkinlik Adı  (Z-A)</a>
                    <a class="dropdown-item" href="?sort=ActivityContentASC">Etkinlik İçeriği (A-Z)</a>
                    <a class="dropdown-item" href="?sort=ActivityContentDESC">Etkinlik İçeriği (Z-A)</a>
                    <a class="dropdown-item" href="?sort=ActivityStartDateASC">Etkinlik Başlangıç Tarihi (Yeni-Eski)</a>
                    <a class="dropdown-item" href="?sort=ActivityStartDateDESC">Etkinlik Başlangıç Tarihi (Eski-Yeni)</a>
                    <a class="dropdown-item" href="?sort=ActivityFinishDateASC">Etkinlik Bitiş Tarihi (Yeni-Eski)</a>
                    <a class="dropdown-item" href="?sort=ActivityFinishDateDESC">Etkinlik Bitiş Tarihi (Eski-Yeni)</a>
                    <a class="dropdown-item" href="?sort=NumberOfPagesDateASC">Okuduğum Sayfa Sayısı (Azdan Çoğa)</a>
                    <a class="dropdown-item" href="?sort=NumberOfPagesDateDESC"> Okuduğum Sayfa Sayısı(Çoktan Aza)</a>
                    <a class="dropdown-item" href="?sort=BookReviewScoreASC"> Etkinlik Puanı(Azdan Çoğa)</a>
                    <a class="dropdown-item" href="?sort=BookReviewScoreDESC"> Etkinlik Puanı(Çoktan Aza)</a>
                </div>
            </div>
            <div class="form-group  col-lg-2">
                <input type="text" id="searchInput" class="form-control" placeholder="Ara...">
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Etkinlik Adı</th>
                        <th>Etkinlik İçeriği</th>
                        <th>Etkinlik Başlangıç Tarihi</th>
                        <th>Etkinlik Bitiş Tarihi</th>
                        <th>Okuduğum Sayfa Sayısı</th>
                        <th>Etkinlik Puanı</th>
                        <th>Güncelle</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.ReadingActivity.ActivityTitle</td>
                        <td>@item.ReadingActivity.ActivityContent</td>
                        <td>@item.ReadingActivity.ActivityStartDate.ToString("dd MMMM yyyy")</td>
                        <td>@item.ReadingActivity.ActivityFinishDate.ToString("dd MMMM yyyy")</td>
                        <td>@item.NumberOfPages</td>
                        <td>@item.BookReviewScore</td>
                        <td><a href="/UserReadingActivity/EditActivity/@item.UserReadingActivityID" class="btn btn-primary">Güncelle</a></td>
                        
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section scripts{
    <script>
    $(document).ready(function () {
        $("#searchInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("table tbody tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
    </script>
}

GroupProject/Views/UserReadingActivity/EditActivity.cshtml
@model EntityLayer.Concrete.UserReadingActivity
@{
    ViewData["Title"] = "EditActivity";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h5 class="m-0 font-weight-bold text-primary">ETKİNLİK BİLGİLERİMİ GÜNCELLE</h5>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("EditActivity", "UserReadingActivity", FormMethod.Post))
        {
            @Html.HiddenFor(x => x.UserReadingActivityID, new { @class = "form-control", Value = @Model.UserReadingActivityID})
            @Html.HiddenFor(x => x.UserID, new { @class = "form-control", Value = @Model.UserID })
            @Html.HiddenFor(x => x.ReadingActivityID, new { @class = "form-control", Value = @Model.ReadingActivityID })
            @Html.HiddenFor(x => x.DateOfRegistration, new { @class = "form-control", Value = @Model.DateOfRegistration })
            <br />

            <div class="row pt-3">
                <div class="col-lg-6">
                    @Html.Label("Okuduğum Sayfa Sayısı")
                    @Html.TextBoxFor(x => x.NumberOfPages, new { @class = "form-control", required = "required" })
                </div>
                <div class="col-lg-6">
                    @Html.Label("Etkinlik Puanı")
                    @Html.TextBoxFor(x => x.BookReviewScore, new { @class = "form-control", required = "required" })
                </div>
            </div>
            <div class="pt-3">
                <button class="btn btn-success pr-4 pl-4 pt-2 pb-2" style="float:right; font-size: 20px"> <i class="fas fa-edit pr-3"></i>GÜNCELLE</button>
            </div>
        }
    </div>
</div>